source 'https://rubygems.org'
ruby '2.3.1'

gem 'active_model_serializers'
gem 'acts-as-taggable-on'
gem 'ancestry'
gem 'autoprefixer-rails'
gem 'aws-sdk', '>= 2.0.0'
gem 'bcrypt', '3.1.7'
gem 'browserify-rails'
gem 'bugsnag'
gem 'capybara'
gem 'coffee-rails', '>= 4.1.1'
gem 'countries'
gem 'country_select'
gem 'devise'
gem 'devise_masquerade'
gem 'devise_token_auth'
gem 'factory_girl_rails', '~> 4.4'
gem 'faker', '1.4.2'
gem 'figaro'
gem 'find_with_order'
gem 'font-awesome-rails'
gem 'friendly_id', '~> 5.1.0'
gem 'google-analytics-rails', '1.1.0'
gem 'gretel'
gem 'haml-rails', '~> 0.9.0'
gem 'hover-rails'
gem 'httparty'
gem 'instagram', '~> 1.1', '>= 1.1.6'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'jwt'
gem 'mechanize'
gem 'mini_magick'
gem 'money-rails'
gem 'nested_form'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-instagram'
gem 'paperclip', '>= 5.0.0'
gem 'pg'
gem 'pg_search'
gem 'phantomjs', require: 'phantomjs/poltergeist'
gem 'poltergeist'
gem 'rack-cors'
gem 'rails', '5.0.1'
gem 'rake', '< 11.0'
gem 'react-rails'
gem 'redis'
gem 'role_model'
gem 'sass-rails', '>= 5.0.5'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sidekiq'
gem 'simple_form'
gem 'thin'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'whenever', require: false # EC2
gem 'will_paginate', '3.1.5'
gem 'zeroclipboard-rails'

group :development, :test do
  gem 'brakeman', require: false
  gem 'haml-lint'
  gem 'massa'
  gem 'pry'
  gem 'rspec-rails', '>= 3.5.0'
  gem 'rubocop', require: false
end

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-npm'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-delayed-job'
  gem 'letter_opener'
  gem 'web-console', '>= 2.3.0'
end

group :test do
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'spring'
end

group :production do
  gem 'rails_12factor'
end
